
name: Clean and Build

on:
  push:
    branches: [ "**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  spotless:
    if: "!contains(github.event.commits[0].message, '[clean push]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Do Nothing
        run: exit 0
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Spotless Apply
        run: ./gradlew spotlessApply
      - name: Commit
        id: commit
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        continue-on-error: true
        run: |
          git config --global user.name "gh-commiter[bot]"
          git config --global user.email 192268280+gh-commiter[bot]@users.noreply.github.com
          git add .
          git commit -m "[clean push] '${{ github.event.head_commit.message }}'"
      - name: Push Branch
        if: ${{ steps.commit.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git push --force
          echo "Push successful"
          exit 1
  build:
    needs: spotless
    if: |
      always() &&
      (needs.spotless.result == 'success' || needs.spotless.result == 'skipped')
      
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      run: |
        ./gradlew build
        echo ${{ needs.spotless.steps.commit.outcome }}
