# This is a basic workflow to build robot code.
name: Clean
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.

on:
  push:
    branches: [ "**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Spotless Apply
        run: ./gradlew spotlessApply
      - name: Commit
        id: commit
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        continue-on-error: true
        run: |
          git config --global user.name "GH Commiter"
          git config --global user.email 123456789+GH Commiter[bot]@users.noreply.github.com
          git add .
          git commit -m "Clean '${{ github.event.head_commit.message }}'"
      - name: Push Branch
        if: ${{ steps.commit.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git push --force
          echo "Push successful"
