
on:
  workflow_dispatch:
  repository_dispatch:
    types: [succession_trigger]

jobs:
  do_nothing:
  # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    steps:
      - name: "As I said"
        run:
          echo "hehe"

