# This is a basic workflow to build robot code.
name: Clean
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.

on:
  push:
    branches: [ "**" ]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Spotless Apply
        run: ./gradlew spotlessApply
      - name: Commit
        id: commit
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'Spotless Commiter'
          git config --global user.email 'SPoovathumkadavil@users.noreply.github.com'
          git commit -am "Clean '${{ github.event.head_commit.message }}'"
      - name: Push Branch
        if: ${{ steps.commit.outcome == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push
          echo "Push successful"
